<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Sothema.Compliance.Application\Sothema.Compliance.Application.csproj" />
    <ProjectReference Include="..\Sothema.Compliance.Infrastructure\Sothema.Compliance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
